// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOSYWe1Nk4JWxm2oC1t7nzrU15CXqDTzk',
    appId: '1:131772921897:web:69b89371bc5dbebf850438',
    messagingSenderId: '131772921897',
    projectId: 'resep-kita-19eb5',
    authDomain: 'resep-kita-19eb5.firebaseapp.com',
    storageBucket: 'resep-kita-19eb5.firebasestorage.app',
    measurementId: 'G-PQ6GHT5KZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn2akmepys8J0TqToki1Fx-mY5SbwZ2GE',
    appId: '1:131772921897:android:a16b5b88e4db0264850438',
    messagingSenderId: '131772921897',
    projectId: 'resep-kita-19eb5',
    storageBucket: 'resep-kita-19eb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD1Nqi4Sf5RfLv9OJun-choq_h_jv6X98',
    appId: '1:131772921897:ios:eba58c24c140e146850438',
    messagingSenderId: '131772921897',
    projectId: 'resep-kita-19eb5',
    storageBucket: 'resep-kita-19eb5.firebasestorage.app',
    iosBundleId: 'com.example.resepKita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD1Nqi4Sf5RfLv9OJun-choq_h_jv6X98',
    appId: '1:131772921897:ios:eba58c24c140e146850438',
    messagingSenderId: '131772921897',
    projectId: 'resep-kita-19eb5',
    storageBucket: 'resep-kita-19eb5.firebasestorage.app',
    iosBundleId: 'com.example.resepKita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOSYWe1Nk4JWxm2oC1t7nzrU15CXqDTzk',
    appId: '1:131772921897:web:4077073241351d27850438',
    messagingSenderId: '131772921897',
    projectId: 'resep-kita-19eb5',
    authDomain: 'resep-kita-19eb5.firebaseapp.com',
    storageBucket: 'resep-kita-19eb5.firebasestorage.app',
    measurementId: 'G-9HVR6CQ07G',
  );
}
